## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage")'
  - julia -e 'using Coverage; import SubstitutionModels; cd(dirname(dirname(pathof(SubstitutionModels)))); Codecov.submit(process_folder())'
  - julia -e 'import SubstitutionModels; cd(dirname(dirname(pathof(SubstitutionModels)))); include(joinpath("docs", "make.jl"))'
