name = "SubstitutionModels"
uuid = "8365b1bb-bd83-58ee-a267-f2965fc81c73"
authors = ["Justin Angevaare <justinangevaare@gmail.com>"]
version = "0.4.1"

[deps]
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
BioSymbols = "3, 4"
StaticArrays = "0.12"
julia = "0.7, 2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
