name: julia-nightly

on: [push, pull_request]

jobs:
  test:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['nightly']
        julia-arch: [x64]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v3
        with:
          delete-old-caches: 'false'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: 'yes'
