name: julia-1.10

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.10']
        julia-arch: [x64]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v3
        with:
          delete-old-caches: 'false'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: 'yes'
      - name: Test normal bounds behavior
        run: julia --project=. --check-bounds=auto --depwarn=yes test/runtests.jl

  minimum:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.0'
      - run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=. test/runtests.jl
      - run: julia --project=. --check-bounds=yes test/runtests.jl
